# Copyright (c) 2020 GeekShop.
# All rights reserved.
database: mysql

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://10.0.4.57:3306/shop}
    username: ${MYSQL_USER:geekshop}
    password: ${MYSQL_PASS:geekshop}
    # SQL is written to be idempotent so this is safe
    initialization-mode: always